POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Adasasd Lovelace",
    "number": "235236235"
}

##########################################

GET http://localhost:3001/api/persons/1 