POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Test Lovelace",
    "number": "0409348174"
}

##########################################

GET http://localhost:3001/api/persons/1 